version: "3"
services:
  web:
    build: .
    ports:
     - "3039:3030"
    volumes:
     - soundboard/:/usr/src/app/public
    container_name: soundboardv2
    restart: always
  db:
    image: mongo
    env_file: .env-mongo
    volumes:
      - mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  soundboard:
  mongo: